name: Build Dev Containers

on:
  push:
    branches: [ main ]
    paths:
      - '**/.devcontainer/**'
      - '**/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - '**/.devcontainer/**'
      - '**/Dockerfile'
  workflow_dispatch:

jobs:
  list-devcontainers:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Find devcontainer directories
        id: set-matrix
        run: |
          # Find directories containing .devcontainer and format for matrix
          # This will find directories like 'base-debian', 'another-container'
          # and create a JSON array like ["base-debian", "another-container"]
          paths=$(find . -path '*/.devcontainer' -printf '%h\n' | sed 's|./||' | jq -Rsc 'split("\n")[:-1]')
          echo "matrix=$paths" >> $GITHUB_OUTPUT
          echo "Found devcontainer paths: $paths"

  build:
    needs: list-devcontainers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        devcontainer_path: ${{fromJson(needs.list-devcontainers.outputs.matrix)}}
      fail-fast: false # Continue building other devcontainers if one fails
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: string_ops
        run: |
          echo "lowercase_repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build dev container for ${{ matrix.devcontainer_path }}
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{ matrix.devcontainer_path }}
          imageName: ghcr.io/${{ steps.string_ops.outputs.lowercase_repo }}/${{ matrix.devcontainer_path }}
          cacheFrom: ghcr.io/${{ steps.string_ops.outputs.lowercase_repo }}/${{ matrix.devcontainer_path }}
          eventFilterForPush: push, workflow_dispatch
          