name: Build Dev Containers

on:
  push:
    branches: [ main ]
    paths:
      - '**/.devcontainer/**'
      - '**/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - '**/.devcontainer/**'
      - '**/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find devcontainer directories
        id: find
        uses: devcontainers/ci@v0.3
        with:
          command: find
          findPath: .
          findPattern: .devcontainer

      - name: Build dev containers
        uses: devcontainers/ci@v0.3
        with:
          command: build
          imageName: ${{ github.repository }}-${{ steps.find.outputs.path }}
          cacheFrom: ${{ github.repository }}-${{ steps.find.outputs.path }}
          push: ${{ github.event_name != 'pull_request' }}
          # Optional: Add any additional build arguments or configuration here
          # buildArgs: |
          #   ARG1=value1
          #   ARG2=value2 